// Code generated by "stringer -type Period"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Weekly-0]
	_ = x[Monthly-1]
	_ = x[Yearly-2]
	_ = x[Daily-3]
}

const _Period_name = "WeeklyMonthlyYearlyDaily"

var _Period_index = [...]uint8{0, 6, 13, 19, 24}

func (i Period) String() string {
	if i < 0 || i >= Period(len(_Period_index)-1) {
		return "Period(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Period_name[_Period_index[i]:_Period_index[i+1]]
}
